### ISSUE TITLE
[plugin-add-fab-id]: adding plugin breaks fab:build

### ISSUE THREAD

**Issue by thejuan** [fab-spec/fab#306] opened 2020-11-29 23:57 UTC
RC8

```
     [Typecheck] Typechecking 3 plugins (in background)…
      [Compiler] Compiling your server.js:
        [rollup] Error: PARSE_ERROR
        [rollup] Failed at:
{
  column: 41,
  file: '/home/adam/hatch/app/node_modules/@fab/plugin-add-fab-id/index.ts',
  line: 7
}
        [rollup] At frame:
5: }
6: 
7: export default ({ Router, ServerContext }: FABRuntime, args = {}) => {
                                            ^
8:   const { header } = {
9:     ...DEFAULT_ARGS,
        [rollup] Stack trace follows:
    Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
    Code: PARSE_ERROR
```

**Comment by geelen** [comment] 2020-12-03 15:56
Something super weird is going on, but I had no tests for that module so I thought something might have broken. So I yak shaved something ridiculous and built a new open source library for writing E2E shell tests oops, but now I can't reproduce:

https://github.com/fab-spec/plugin-add-fab-id/blob/master/tests/public.test.ts

This passes fine: https://github.com/fab-spec/plugin-add-fab-id/runs/1493640228#step:6:57

Looking at your error message a little more closely, it seems that rollup isn't stripping typescript definitions off the file. Which means somehow the rollup config is broken, or the `@rollup/plugin-typescript` plugin isn't being found...

**Comment by geelen** [comment] 2020-12-03 15:57
Gonna close this as I can't reproduce it but if you figure out what went wrong maybe rename this issue and reopen?

**Comment by geelen** [comment] 2020-12-04 11:41
Damn, got a reproduction: https://github.com/fab-spec/plugin-add-fab-id/pull/2

**Comment by geelen** [comment] 2020-12-10 08:14
Closing in favour of #311

**Closed by geelen** 2020-12-10 08:14 UTC
